# Configuration file for continuous testing via Travis

language: python

os:
  - linux

matrix:
  include:
    - python: 3.7

before_install:
  - openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d

install:
  - pip install -r requirements.txt
  - python setup.py install

  # Extra dependencies for running tests not included by the tested package
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov

script:
  - coverage run -m pytest
