bootstrap.servers: 'pkc-epgnk.us-central1.gcp.confluent.cloud:9092'
default.topic.config: {auto.offset.reset: smallest}
api.version.request: True
broker.version.fallback: 0.10.0.0
api.version.fallback.ms: 0
sasl.mechanisms: PLAIN
security.protocol: SASL_SSL
sasl.username: 4C2BCMDC4PSC6D4B
sasl.password: Ni9u1ykSVgyOnlgzorpyI8uYDAuozcfZ6wx4LqtsML7BPo0nPuEJHQTAbQ+LDXNC
